name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }} 
          mask-aws-account-id: 'no'

      name: Update locals.tf
      run: |
        awk '/^}/ { print "  bastion_key_private = \"" ENVIRON["BASTION_PRIVATE_KEY"] "\"" }1' locals.tf > locals.tf.tmp
        awk '/^}/ { print "  nginx_key_private = \"" ENVIRON["NGINX_PRIVATE_KEY"] "\"" }1' locals.tf.tmp > locals.tf
        rm locals.tf.tmp
      shell: bash
      env:
        BASTION_PRIVATE_KEY: ${{ secrets.BASTION_PRIVATE_KEY }}
        NGINX_PRIVATE_KEY: ${{ secrets.NGINX_PRIVATE_KEY }}

      - name: Terraform Init 
        run: |
          terraform init
        working-directory: ./tf

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
        working-directory: ./tf
